### ISSUE TITLE
Refuses to load created config file

### ISSUE THREAD

**Issue by iwarford** [masak/proto#1]
August 2009 release creates a config file with July 2009 date, subsequently refuses to load it because it's too old.

**Comment by masak** [comment]
Thank you; this is now fixed.

That deprecation note was meant to be the first step in a series of wide-ranging changes to how proto handles installed modules. Unfortunately, the deprecation notice was all I had time for this week -- the new way of installing things will have to await fresh tuits. Until then, I reverted the deprecation message so that people can keep using proto in the old way.
